### ISSUE TITLE
Urgently need to change account login in teams. No way to do this!

### ISSUE THREAD

**Issue by ChrisSutton46** [enovation/moodle-atto_teamsmeeting#17]
I have successfully installed the Plugin - love it but now have a huge problem. My login to Teams has changed and I have a new username and password. (I administer Teams as a sole tutor using Moodle as a platform). 

The plugin keeps wanting to go to the old login and I cannot find any way of changing it to the new one. I tried to uninstall and reinstall but that didn't happen - I received a "this plugin cannot be uninstalled" message. HELP!!! How can I reset the 365 Teams login?

**Comment by avegys** [comment]
Hi Chris,

This happens because your browser keeps your office365 session and this is not related to plugin at all. To log out you can go to https://login.microsoftonline.com and sign out there. Then you will be signed out from office365 and be able to login with different account when accessing any of office365 services.

Best regards,
Andrius

**Comment by ChrisSutton46** [comment]
Thanks Andreus, I’ll give that a try.

 

Cheers

Chris
