### ISSUE TITLE
ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by vassper888** [enovation/moodle-atto_teamsmeeting#43]
When creating a conference, an ERR_CONNECTION_CLOSED error appears https://disk.yandex.ru/i/fLekMeR-33HXNQ .
The problem is due to the fact that too large a value is returned in the get parameter "preview".
GET request, together with the domain and other parameters, is more than 9000 characters long.

**Comment by vassper888** [comment]
server {
   http2_max_field_size 64k;
   http2_max_header_size 64k;
}

**Comment by tonyjbutler** [comment]
We've been experiencing this at Lancaster University too, since Tuesday. I wonder if something has changed on the enovation.ie side this week, but as you say those params are now huge.
Unfortunately the nginx config above doesn't seem to work for our proxies, and the same applies to other settings I've found online that seem like they should help with this kind of issue.
So I'm now wondering what other approach we could take, such as making a change to the code to use a POST rather than a GET for example.

**Comment by lalitm14** [comment]
yes, thank you .... with 3K & 32K setting the Team meeting worked. I haven't tested 64K for each of these parameters
